# Generated by Django 5.2.3 on 2025-06-29 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterrole',
            name='added_by_user',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='added_roles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='chapterrole',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='roles',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='chapterrole',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='chapter_roles',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='chaptersociallink',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='social_links',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='chapterzip',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='zips',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='history_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='state',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='regions.state',
            ),
        ),
        migrations.AddField(
            model_name='historicalchaptersociallink',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='historicalchaptersociallink',
            name='history_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicalofflinetotal',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='historicalofflinetotal',
            name='history_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicalofflinetotal',
            name='submitted_by_user',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='offlinetotal',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='offline_totals',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='offlinetotal',
            name='submitted_by_user',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='chapterrole',
            constraint=models.UniqueConstraint(
                fields=('user', 'chapter'), name='chapter_role_unique_user_role'
            ),
        ),
    ]
