# Generated by Django 5.2 on 2025-05-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterzip',
            name='state_code',
        ),
        migrations.AlterField(
            model_name='chapterzip',
            name='zip_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='chapters',
                to='regions.zip',
            ),
        ),
    ]
