# Generated by Django 5.2 on 2025-05-31 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_initial'),
        ('regions', '0003_rename_irs_estimated_population_zip_population_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterzip',
            name='id',
        ),
        migrations.AlterField(
            model_name='chapterzip',
            name='zip_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name='chapters',
                serialize=False,
                to='regions.zip',
            ),
        ),
    ]
