# Generated by Django 5.2 on 2025-05-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterzip',
            options={'ordering': ('zip_code',), 'verbose_name': 'Chapter ZIP'},
        ),
    ]
