# Generated by Django 5.2 on 2025-05-31 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_remove_chapterzip_id_alter_chapterzip_zip_code'),
        ('regions', '0003_rename_irs_estimated_population_zip_population_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterzip',
            name='chapter',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='zip',
                to='chapters.chapter',
            ),
        ),
        migrations.AlterField(
            model_name='chapterzip',
            name='zip_code',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name='chapter',
                serialize=False,
                to='regions.zip',
            ),
        ),
    ]
