# Generated by Django 5.2 on 2025-05-14 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_remove_chapterzip_state_code_and_more'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterstate',
            name='state_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='chapters',
                to='regions.state',
            ),
        ),
    ]
