# Generated by Django 5.2 on 2025-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'chapters',
            '0003_rename_historicalpapertotal_historicalofflinetotal_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='nearby_chapters',
            field=models.ManyToManyField(to='chapters.chapter'),
        ),
    ]
