# Generated by Django 5.2 on 2025-05-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapterstate_state_code'),
        ('regions', '0002_alter_zip_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterzip',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterzip',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='chapter',
            name='states',
            field=models.ManyToManyField(related_name='chapters', to='regions.state'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='zips',
            field=models.ManyToManyField(related_name='chapters', to='regions.zip'),
        ),
        migrations.DeleteModel(
            name='ChapterState',
        ),
        migrations.DeleteModel(
            name='ChapterZip',
        ),
    ]
