# Generated by Django 5.2 on 2025-05-31 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_alter_chapterzip_chapter_alter_chapterzip_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterzip',
            name='chapter',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='zips',
                to='chapters.chapter',
            ),
        ),
    ]
