# Generated by Django 5.2 on 2025-05-31 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_alter_chapterzip_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterzip',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='zips',
                to='chapters.chapter',
            ),
        ),
    ]
