# Generated by Django 5.2.2 on 2025-06-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_remove_chapterzip_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='nearby_chapters',
            field=models.ManyToManyField(blank=True, to='chapters.chapter'),
        ),
    ]
