# Generated by Django 5.2 on 2025-05-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'chapters',
            '0005_remove_chapterzip_chapter_remove_chapterzip_zip_code_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterrole',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
