# Generated by Django 5.2 on 2025-05-14 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_alter_chapterrole_title'),
        ('regions', '0003_alter_state_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='zips',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='states',
            field=models.ManyToManyField(
                blank=True, related_name='chapters', to='regions.state'
            ),
        ),
        migrations.CreateModel(
            name='ChapterZip',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('total', models.IntegerField(default=0)),
                (
                    'chapter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='zips',
                        to='chapters.chapter',
                    ),
                ),
                (
                    'state',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='regions.state'
                    ),
                ),
                (
                    'zip_code',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='chapters',
                        to='regions.zip',
                    ),
                ),
            ],
        ),
    ]
