# Generated by Django 5.2.2 on 2025-06-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_alter_chapter_nearby_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='total_contacts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='total_contacts',
            field=models.IntegerField(default=0),
        ),
    ]
