# Generated by Django 5.2 on 2025-06-01 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_alter_chapterzip_chapter'),
        ('regions', '0003_rename_irs_estimated_population_zip_population_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('state__name', 'title')},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='states',
        ),
        migrations.AddField(
            model_name='chapter',
            name='state',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='chapters',
                to='regions.state',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='state',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='regions.state',
            ),
        ),
        migrations.AlterField(
            model_name='chapterzip',
            name='zip_code',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                primary_key=True,
                related_name='chapter',
                serialize=False,
                to='regions.zip',
                verbose_name='ZIP',
            ),
        ),
    ]
