# Generated by Django 5.2 on 2025-05-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_remove_chapter_zips_alter_chapter_states_chapterzip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterzip',
            name='total',
        ),
    ]
