# Generated by Django 5.2.2 on 2025-06-23 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_total_contacts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapterrole',
            constraint=models.UniqueConstraint(
                fields=('user', 'chapter'), name='chapter_role_unique_user_role'
            ),
        ),
    ]
