services:
  app:
    image: python:3.12-slim
    container_name: app
    working_dir: /starfish
    volumes:
      - ./starfish:/starfish
    command: sh -c 'cd /starfish && pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir -r requirements_dev.txt && /starfish/dev.sh'
    ports:
      - 8000:8000
