[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true

[tool.flake8]
extend-exclude = [
  "*/.venv/*.py",
  "*/tests.py",
  "*/tests/*.py",
  "starfish/*settings*.py",
  "starfish/regions/management/commands/import_zipcodes.py",
]
extend-ignore = "E501"
per-file-ignores = "*/apps.py:F401"
