# Generated by Django 5.2 on 2025-05-07 23:43

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseContactRecord',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    'email_hash',
                    models.CharField(db_index=True, editable=False, max_length=128),
                ),
                (
                    'phone_hash',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=128,
                        null=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'basecontactrecord_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='contacts.basecontactrecord',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('referer_full', models.TextField(blank=True, null=True)),
                (
                    'referer_host',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_token', models.CharField(max_length=64)),
                ('validation_expires_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('contacts.basecontactrecord',),
        ),
        migrations.CreateModel(
            name='ExpungedContact',
            fields=[
                (
                    'basecontactrecord_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='contacts.basecontactrecord',
                    ),
                ),
                ('validated_at', models.DateTimeField()),
                ('expunged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('contacts.basecontactrecord',),
        ),
        migrations.CreateModel(
            name='RemovedContact',
            fields=[
                (
                    'basecontactrecord_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='contacts.basecontactrecord',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('unsubscribed', 'Unsubscribed'),
                            ('deleted', 'Deleted'),
                            ('bounced', 'Bounced'),
                        ],
                        max_length=20,
                    ),
                ),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('contacts.basecontactrecord',),
        ),
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                (
                    'basecontactrecord_ptr',
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name='+',
                        to='contacts.basecontactrecord',
                    ),
                ),
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    'email_hash',
                    models.CharField(db_index=True, editable=False, max_length=128),
                ),
                (
                    'phone_hash',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=128,
                        null=True,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('referer_full', models.TextField(blank=True, null=True)),
                (
                    'referer_host',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_token', models.CharField(max_length=64)),
                ('validation_expires_at', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                (
                    'history_type',
                    models.CharField(
                        choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                        max_length=1,
                    ),
                ),
                (
                    'chapter',
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='+',
                        to='chapters.chapter',
                    ),
                ),
            ],
            options={
                'verbose_name': 'historical contact',
                'verbose_name_plural': 'historical contacts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
