# Generated by Django 5.2 on 2025-05-29 18:42

import django.db.models.deletion
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import contacts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0002_initial'),
        ('contacts', '0001_initial'),
        ('partners', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcontact',
            name='history_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='zip_code',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='regions.zip',
            ),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'basecontact_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='contacts.basecontact',
                    ),
                ),
                ('validated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-validated',),
            },
            bases=('contacts.basecontact',),
        ),
        migrations.CreateModel(
            name='PendingContact',
            fields=[
                (
                    'basecontact_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='contacts.basecontact',
                    ),
                ),
                (
                    'validation_token',
                    model_utils.fields.UrlsafeTokenField(
                        blank=True,
                        editable=False,
                        factory=None,
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    'validation_expires',
                    models.DateTimeField(
                        blank=True,
                        default=contacts.models._get_validation_expires,
                        null=True,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('contacts.basecontact',),
        ),
        migrations.AddField(
            model_name='basecontact',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contacts',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='basecontact',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contacts',
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='basecontact',
            name='zip_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contacts',
                to='regions.zip',
            ),
        ),
        migrations.AddField(
            model_name='expungedcontact',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expunged_contacts',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='expungedcontact',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='removedcontact',
            name='removed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
