# Generated by Django 5.2 on 2025-05-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontact',
            name='zip_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contacts',
                to='regions.zip',
            ),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='zip_code',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='regions.zip',
            ),
        ),
    ]
