# Generated by Django 5.2 on 2025-06-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactnote',
            options={'verbose_name': 'Note'},
        ),
        migrations.AddField(
            model_name='contact',
            name='engagement_level',
            field=models.SmallIntegerField(
                blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True
            ),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='engagement_level',
            field=models.SmallIntegerField(
                blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True
            ),
        ),
    ]
