# Generated by Django 5.2 on 2025-05-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontact',
            name='referer_full',
            field=models.TextField(blank=True, null=True, verbose_name='Referrer'),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='referer_full',
            field=models.TextField(blank=True, null=True, verbose_name='Referrer'),
        ),
    ]
