# Generated by Django 5.2 on 2025-05-16 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'chapters',
            '0009_alter_chapterzip_options_alter_chapter_website_url_and_more',
        ),
        ('contacts', '0003_alter_basecontact_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontact',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='contacts',
                to='chapters.chapter',
            ),
        ),
    ]
