# Generated by Django 5.2 on 2025-05-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_basecontact_referer_full_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecontact',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-validated',)},
        ),
    ]
