# Generated by Django 5.2 on 2025-06-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'contacts',
            '0003_alter_contactnote_options_contact_engagement_level_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='engagement_level',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='engagement_level',
        ),
        migrations.AddField(
            model_name='contact',
            name='leadership_score',
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                null=True,
                verbose_name='Leadership',
            ),
        ),
        migrations.AddField(
            model_name='historicalcontact',
            name='leadership_score',
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                null=True,
                verbose_name='Leadership',
            ),
        ),
    ]
