# Generated by Django 5.2.2 on 2025-06-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_engagement_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hashedcontactrecord',
            name='email_hash',
            field=models.CharField(
                db_index=True, editable=False, max_length=128, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='historicalcontact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pendingcontact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
