# Generated by Django 5.2 on 2025-05-29 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_basecontact_options_alter_contact_options'),
        ('partners', '0003_historicalpledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecontact',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='contacts',
                to='partners.partnercampaign',
            ),
        ),
    ]
