# Generated by Django 5.2 on 2025-05-17 03:57

import model_utils.fields
from django.db import migrations, models

import contacts.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_basecontact_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecontact',
            name='validation_expires',
        ),
        migrations.RemoveField(
            model_name='basecontact',
            name='validation_token',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='validation_expires',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='validation_token',
        ),
        migrations.AddField(
            model_name='pendingcontact',
            name='validation_expires',
            field=models.DateTimeField(
                blank=True, default=contacts.models._get_validation_expires, null=True
            ),
        ),
        migrations.AddField(
            model_name='pendingcontact',
            name='validation_token',
            field=model_utils.fields.UrlsafeTokenField(
                blank=True, editable=False, factory=None, max_length=128, null=True
            ),
        ),
    ]
