# Generated by Django 5.2.2 on 2025-06-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashedcontactrecord',
            name='phone_hash',
        ),
        migrations.RemoveField(
            model_name='historicalcontact',
            name='phone_hash',
        ),
    ]
