# Generated by Django 5.2.2 on 2025-06-28 05:10

import contacts.models
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_remove_hashedcontactrecord_phone_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcontact',
            name='validation_expires',
            field=models.DateTimeField(default=contacts.models._get_validation_expires),
        ),
        migrations.AlterField(
            model_name='pendingcontact',
            name='validation_token',
            field=model_utils.fields.UrlsafeTokenField(
                editable=False, factory=None, max_length=32
            ),
        ),
    ]
