# Generated by Django 5.2 on 2025-05-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartnercampaign',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partnercampaign',
            name='description',
        ),
        migrations.AddField(
            model_name='historicalpartnercampaign',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnercampaign',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpartnercampaign',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='partnercampaign',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
