# Generated by Django 5.2 on 2025-05-19 03:12

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='created',
            ),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='modified',
            ),
        ),
        migrations.AddField(
            model_name='historicalaffiliate',
            name='created',
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='created',
            ),
        ),
        migrations.AddField(
            model_name='historicalaffiliate',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalaffiliate',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name='modified',
            ),
        ),
    ]
