# Generated by Django 5.2 on 2025-06-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpartnercampaign',
            name='key_string',
        ),
        migrations.RemoveField(
            model_name='partnercampaign',
            name='key_string',
        ),
        migrations.AddField(
            model_name='historicalpartnercampaign',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnercampaign',
            name='slug',
            field=models.SlugField(default=' ', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
