# Generated by Django 5.2 on 2025-05-09 00:09

import django.db.models.deletion
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpartnercampaign',
            name='key_string',
            field=model_utils.fields.UrlsafeTokenField(
                db_index=True, editable=False, factory=None, max_length=16
            ),
        ),
        migrations.AlterField(
            model_name='partnercampaign',
            name='key_string',
            field=model_utils.fields.UrlsafeTokenField(
                editable=False, factory=None, max_length=16, unique=True
            ),
        ),
        migrations.CreateModel(
            name='AffiliatedPledge',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('organization_name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'submitted_by_user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
