# Generated by Django 5.2 on 2025-06-01 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                (
                    'code',
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                (
                    'code',
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ('type', models.CharField(max_length=20)),
                (
                    'primary_city',
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ('acceptable_cities', models.TextField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('area_codes', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                (
                    'state',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='regions.state'
                    ),
                ),
            ],
            options={
                'verbose_name': 'ZIP Code',
                'ordering': ('code',),
            },
        ),
    ]
