# Generated by Django 5.2 on 2025-05-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                (
                    'code',
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                (
                    'code',
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                (
                    'state',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='regions.state'
                    ),
                ),
            ],
            options={
                'verbose_name': 'ZIP Code',
                'ordering': ('code',),
            },
        ),
    ]
