# Generated by Django 5.2 on 2025-05-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zip',
            options={'ordering': ('code',)},
        ),
    ]
