# Generated by Django 5.2 on 2025-05-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='acceptable_cities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='area_codes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='irs_estimated_population',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='primary_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zip',
            name='type',
            field=models.CharField(default='STANDARD', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zip',
            name='unacceptable_cities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
