# Generated by Django 5.2 on 2025-05-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_alter_zip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name',)},
        ),
    ]
