# Generated by Django 5.2 on 2025-05-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_zip_acceptable_cities_zip_area_codes_zip_county_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zip',
            old_name='irs_estimated_population',
            new_name='population',
        ),
        migrations.RemoveField(
            model_name='zip',
            name='unacceptable_cities',
        ),
    ]
