# Generated by Django 5.2 on 2025-05-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_state_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='id',
        ),
        migrations.AlterField(
            model_name='zip',
            name='code',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
