# Generated by Django 5.2 on 2025-05-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_remove_zip_id_alter_zip_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zip',
            options={'ordering': ('code',), 'verbose_name': 'ZIP Code'},
        ),
    ]
