# Generated by Django 5.2.3 on 2025-06-29 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0002_initial'),
        ('members', '0001_initial'),
        ('partners', '0001_initial'),
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membernote',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='member_notes',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='history_user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='historicalmember',
            name='zip_code',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='regions.zip',
            ),
        ),
        migrations.AddField(
            model_name='membernote',
            name='member',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notes',
                to='members.member',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)ss',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(class)ss',
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)ss',
                to='regions.zip',
            ),
        ),
        migrations.AddField(
            model_name='expungedmember',
            name='chapter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='expunged_members',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='expungedmember',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='pendingmember',
            name='chapter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)ss',
                to='chapters.chapter',
            ),
        ),
        migrations.AddField(
            model_name='pendingmember',
            name='partner_campaign',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(class)ss',
                to='partners.partnercampaign',
            ),
        ),
        migrations.AddField(
            model_name='pendingmember',
            name='zip_code',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='%(class)ss',
                to='regions.zip',
            ),
        ),
        migrations.AddField(
            model_name='removedmember',
            name='removed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
